version: 2
jobs:
  build:
    working_directory: /setlr
    docker:
      - image: python:3.7-stretch
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip3 install -e .
            pip3 install nose2
      - run:
          name: Run tests
          command: python3 -m unittest tests/setlr_test/test_read_json.py
  lint:
    working_directory: /setlr
    docker:
      - image: python:3.7-stretch
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip3 install flake8 pycodestyle pylint vulture
      - run:
          name: Lint the code
          command: .circleci/lint.sh
      - store_artifacts:
          path: lint-results
workflows:
  version: 2
  build_lint:
    jobs:
      - build
      - lint

